### ISSUE TITLE
Unconex Allowed Difference Argument

### ISSUE THREAD

**Issue by johnridge** [rotsehub/rotseana#3]
[11-16-2019 Meeting.pdf](https://github.com/rotsehub/rotseana/files/3854634/11-16-2019.Meeting.pdf)
Unconex is removing significant quantities of non-discrepant observations due to the difference between epochs exceeding the hardcoded allowed difference. An argument should be added to account for this.

**Comment by GrantPDonnelly** [comment]
John modified unconex to allow the user to input the "allowed difference" between epochs on the command line.
