### ISSUE TITLE
Change in Chisq Binary 

### ISSUE THREAD

**Issue by Gakehoe** [rotsehub/rotseana#38]
Hi @rkehoe i have changed the main and shortened it by a decent amount. Can you look at my code and tell me if something should be fixed?

**Comment by Gakehoe** [comment]
hey @jjuvan could you test my new code? I have pushed the code into github so you should be able to run it with one of your files now. It may not run properly and will crash but that will mostly be due to certain numbers hardcoded in.

**Comment by rkehoe** [comment]
I am closing this issue with a comment as it is part of the recent PR that was just merged.
